#!/bin/tcsh
# GitHub Actions Status Checker
# Provides multiple ways to monitor workflow status

echo "🔍 GitHub Actions Status Checker"
echo "================================"
echo ""

set repository_dir = "/home/sdodl001/GenomicLightning"
cd $repository_dir

echo "📅 Last push information:"
echo "------------------------"
echo "Repository: https://github.com/SanjeevaRDodlapati/GenomicLightning"
echo "Latest commit:"
git log --oneline -1
echo "Push time: `git log -1 --format=%cd`"
echo ""

echo "🌐 MONITORING METHODS:"
echo "====================="
echo ""

echo "METHOD 1: Direct GitHub Web Interface (RECOMMENDED)"
echo "---------------------------------------------------"
echo "🔗 Actions Dashboard: https://github.com/SanjeevaRDodlapati/GenomicLightning/actions"
echo ""
echo "Visual Status Indicators:"
echo "  🟢 Green checkmark (✓) = SUCCESS"
echo "  🔴 Red X (✗) = FAILED"
echo "  🟡 Yellow dot (●) = IN PROGRESS"
echo "  ⚪ Gray circle (○) = QUEUED/PENDING"
echo "  🔵 Blue dot = SKIPPED"
echo ""
echo "Look for workflows triggered by commit: 'feat: achieve perfect 10/10 deployment readiness'"
echo ""

echo "METHOD 2: GitHub CLI (if installed)"
echo "----------------------------------"
echo "If you have GitHub CLI installed, run:"
echo "gh run list --repo SanjeevaRDodlapati/GenomicLightning"
echo "gh run view --repo SanjeevaRDodlapati/GenomicLightning"
echo ""

echo "METHOD 3: Email Notifications"
echo "-----------------------------"
echo "GitHub sends email notifications for workflow failures to:"
echo "- Repository owner"
echo "- Commit author"
echo "- Users watching the repository"
echo ""
echo "Check your email for notifications from GitHub Actions"
echo ""

echo "METHOD 4: Commit Status API (Advanced)"
echo "-------------------------------------"
echo "API endpoint to check commit status:"
echo "https://api.github.com/repos/SanjeevaRDodlapati/GenomicLightning/commits/`git rev-parse HEAD`/status"
echo ""

echo "METHOD 5: Repository Badges"
echo "---------------------------"
echo "If repository has status badges, check the README or:"
echo "https://github.com/SanjeevaRDodlapati/GenomicLightning"
echo ""

echo "🕐 TIMELINE EXPECTATIONS:"
echo "========================"
echo "⏱️  Workflow start: 1-2 minutes after push"
echo "⏱️  Full completion: 10-15 minutes"
echo "⏱️  Push time: `git log -1 --format=%cd`"
echo "⏱️  Expected completion: `date -d '+15 minutes' -d \"$(git log -1 --format=%cd)\"`"
echo ""

echo "🚨 FAILURE INDICATORS:"
echo "======================"
echo "❌ Red X next to workflow name"
echo "📧 Email notification with 'failed' in subject"
echo "🔴 Failed status on commit in GitHub"
echo "⚠️  Error badges in repository README"
echo ""

echo "✅ SUCCESS INDICATORS:"
echo "====================="
echo "✅ Green checkmarks on all workflow jobs"
echo "📧 No failure emails received"
echo "🟢 All checks passed on commit"
echo "✨ Green status badges in README"
echo ""

echo "🔧 TROUBLESHOOTING FAILED WORKFLOWS:"
echo "===================================="
echo "If you see failures:"
echo ""
echo "1. Click on the failed workflow in GitHub Actions"
echo "2. Click on the failed job"
echo "3. Expand the failed step to see error logs"
echo "4. Common failure patterns to look for:"
echo "   - Import errors (module not found)"
echo "   - Test failures (assertion errors)"
echo "   - Dependency conflicts (version incompatibility)"
echo "   - Linting errors (code style issues)"
echo "   - Environment setup failures"
echo ""

echo "📊 CURRENT STATUS CHECK:"
echo "========================"
echo "To check right now:"
echo "1. Open: https://github.com/SanjeevaRDodlapati/GenomicLightning/actions"
echo "2. Look for the latest workflow run"
echo "3. Check the status icons"
echo ""

echo "Expected workflows that should be running/completed:"
echo "- GenomicLightning CI/CD Pipeline"
echo "- GenomicLightning Testing Infrastructure"
echo ""

echo "🔄 AUTO-REFRESH MONITORING:"
echo "============================"
echo "Run this script periodically:"
echo "tcsh check_workflow_status.csh"
echo ""
echo "Or set up a watch command:"
echo "watch -n 30 'tcsh check_workflow_status.csh'"
echo ""

echo "📱 MOBILE MONITORING:"
echo "===================="
echo "You can also check on mobile:"
echo "- GitHub mobile app"
echo "- Browser: https://github.com/SanjeevaRDodlapati/GenomicLightning/actions"
echo ""

echo "🎯 QUICK STATUS SUMMARY:"
echo "========================"
echo "✅ Push successful: YES"
echo "🔄 Workflows triggered: YES" 
echo "⏰ Expected completion: ~15 minutes from push time"
echo "🌐 Monitor at: https://github.com/SanjeevaRDodlapati/GenomicLightning/actions"
